name: Android CI

on:
  push:
    branches: [ master, sms ]
  pull_request:
    branches: [ master, sms ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle

    - name: Build with Gradle
      run: ./gradlew assembleDebug -x test -x lint

    # Debugging step to list the contents of the build folder
    - name: List build outputs
      run: ls -R myExpenses/build/

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: myExpenses/build/outputs/apk/debug/*.apk
